name: whatsup
title: WhatsUp
base: core24
version: '0.1'
summary: A WhatsApp wrapper using QtWebEngine, and Kirigami
description: |
  "Whatsup" is a desktop client for WhatsApp designed to integrate with the KDE Plasma desktop environment. It acts as a "wrapper" for the web version of WhatsApp, providing a more native-like experience for users on Linux.

grade: stable
confinement: strict

license: GPL-3.0-or-later
contact: soumyadeepghosh2004+whatsup@zohomail.in
issues: https://invent.kde.org/soumyadghosh/whatsup/-/issues
website: https://invent.kde.org/soumyadghosh/whatsup
source-code: https://invent.kde.org/soumyadghosh/whatsup
donation: http://github.com/soumyaDghosh/sponsors

platforms:
  amd64:


parts:
  uap-cpp:
    plugin: cmake
    source: https://github.com/ua-parser/uap-cpp.git
    source-depth: 1
    build-snaps:
      - cmake
    build-packages:
      - libre2-dev
      - libyaml-cpp-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTS=OFF
    override-build: |
      craftctl default
      install -Dm644 $CRAFT_PART_SRC/UaParser -t $CRAFT_PART_INSTALL/usr/include/uap-cpp/

  uap-qt:
    after: [uap-cpp]
    plugin: cmake
    source: https://github.com/soumyaDghosh/uap-qt.git
    source-depth: 1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release

  whatsup:
    after: [uap-cpp, uap-qt]
    plugin: cmake
    source: https://invent.kde.org/soumyadghosh/whatsup.git
    source-depth: 1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
    override-pull: |
      craftctl default
      sed -i '/ecm_find_qmlmodule(org.kde.kirigami REQUIRED)/d' CMakeLists.txt
    stage-packages:
      - libyaml-cpp0.8
      - libre2-10

plugs:
  shared-memory:
    private: true

apps:
  whatsup:
    command: usr/bin/whatsup
    extensions: [kde-neon-6]
    common-id: io.github.soumyadghosh.whatsup
    environment:
      QTWEBENGINE_DISABLE_SANDBOX: 1
    plugs:
      - audio-playback
      - audio-record
      - camera
      - network-bind
      - screen-inhibit-control
      - home
      - mpris
